### PR TITLE
Rearranged so await component resolves correctly

### PR DESCRIPTION
**Pull request by imagolive**
Await was not resolving. Had a go at rearranging it so it resolves correctly.

Not sure if this is the right way. Never modified an add-on like this.

### CODE REVIEW

**Comment by Exelord** [comment]
Could to describe the issue a bit more? 🤔

**Comment by knownasilya** [comment]
Addons cannot have folders when reexporting components in app folder.

**Comment by Exelord** [comment]
Hmm... Im wondering why dummy app works then. 🤔

**Comment by knownasilya** [comment]
Yeah, it's inconsistent, hence not recommend. Bug somewhere in resolver.

**Comment by Exelord** [comment]
I tested that in a new app and everything works as expected. I need more details what is exactly not working, and in which ember's version

**Comment by knownasilya** [comment]
It might be if the app is using pods? Mine is. Latest version.

**Comment by Exelord** [comment]
Hmm... I work on app which use pods, and addons with the same export pattern. That works too. The issue needs to be somewhere else. 🤔

**Comment by knownasilya** [comment]
Are you using podModulePrefix? Mine is set

**Comment by Exelord** [comment]
Confirmed podModulePrefix is the issue. Pods without this option work fine as well as classic structure. I think that issue should be reported in ember-cli repo.

**Comment by Exelord** [comment]
For now, lets use this one as hotfix for the issue

**Pull request merged**
